version: "3.9"

services:
    nginx:
        build:
            context: docker/nginx
        ports:
            - "9009:80"
        volumes:
            - ./bff:/srv/bff
        depends_on:
            -   php-fpm
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            -   ./bff:/srv/bff